# Generated by Django 5.0.2 on 2025-11-15 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('CDS', 'Computing and Data Science')], max_length=3)),
                ('subject', models.CharField(choices=[('DS', 'Data Science')], max_length=2)),
                ('catalog_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(choices=[('PLM', "Philosophical Inquiry and Life's Meaning"), ('AEX', 'Aesthetic Exploration'), ('HCO', 'Historical Consciousness'), ('SI1', 'Scientific Inquiry 1'), ('SI2', 'Scientific Inquiry 2'), ('SO1', 'Social Inquiry 1'), ('SO2', 'Social Inquiry 2'), ('QR1', 'Quantitative Reasoning 1'), ('QR2', 'Quantitative Reasoning 2'), ('IIC', 'Individual in the Community'), ('GCI', 'Global Citizenship and Interpersonal Literacy'), ('ETR', 'Ethical Reasoning'), ('FYW', 'First-Year Writing Seminar'), ('WRI', 'Writing, Research, and Inquiry'), ('WIN', 'Writing Intensive Course'), ('OSC', 'Oral and/or Signed Communication'), ('DME', 'Digital/Multimedia Expression'), ('CRT', 'Critical Thinking'), ('RIL', 'Research and Information Literacy'), ('TWC', 'Teamwork/Collaboration'), ('CRI', 'Creativity/Innovation')], max_length=3)),
            ],
        ),
        migrations.AddConstraint(
            model_name='classdata',
            constraint=models.UniqueConstraint(fields=('college', 'subject', 'catalog_number'), name='unique_classdata'),
        ),
        migrations.AddField(
            model_name='course',
            name='class_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.classdata'),
        ),
        migrations.AddField(
            model_name='course',
            name='hubs',
            field=models.ManyToManyField(to='Core.hub'),
        ),
    ]
