# Generated by Django 5.0.2 on 2025-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_hub_unit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classdata',
            options={'verbose_name_plural': 'Class Data'},
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(blank=True, default=4),
        ),
    ]
