# Generated by Django 5.0.2 on 2025-11-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_classdata_options_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdata',
            name='catalog_number',
            field=models.CharField(max_length=5),
        ),
    ]
