# Generated by Django 5.0.2 on 2025-11-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_classdata_college_alter_classdata_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdata',
            name='college',
            field=models.CharField(choices=[('BUA', 'BU Academy'), ('CDS', 'Faculty of Computing and Data Science'), ('CAS', 'College of Arts and Sciences'), ('COM', 'College of Communication'), ('ENG', 'College of Engineering'), ('CFA', 'College of Fine Arts'), ('CGS', 'College of General Studies'), ('QST', 'Questrom School of Business'), ('SAR', 'Sargent College of Health and Rehabilitation'), ('SHA', 'School of Hospitality Administration'), ('SPH', 'School of Public Health'), ('WED', 'Wheelock College of Education'), ('MET', 'Metropolitan College'), ('KHC', 'Kilichand Honors College')], max_length=3),
        ),
        migrations.AlterField(
            model_name='hub',
            name='unit_name',
            field=models.CharField(choices=[('PLM', "Philosophical Inquiry and Life's Meanings"), ('AEX', 'Aesthetic Exploration'), ('HCO', 'Historical Consciousness'), ('SI1', 'Scientific Inquiry 1'), ('SI2', 'Scientific Inquiry 2'), ('SO1', 'Social Inquiry 1'), ('SO2', 'Social Inquiry 2'), ('QR1', 'Quantitative Reasoning 1'), ('QR2', 'Quantitative Reasoning 2'), ('IIC', 'Individual in the Community'), ('GCI', 'Global Citizenship and Interpersonal Literacy'), ('ETR', 'Ethical Reasoning'), ('FYW', 'First-Year Writing Seminar'), ('WRI', 'Writing, Research, and Inquiry'), ('WIN', 'Writing Intensive Course'), ('OSC', 'Oral and/or Signed Communication'), ('DME', 'Digital/Multimedia Expression'), ('CRT', 'Critical Thinking'), ('RIL', 'Research and Information Literacy'), ('TWC', 'Teamwork/Collaboration'), ('CRI', 'Creativity/Innovation')], max_length=3, unique=True),
        ),
    ]
