# Generated by Django 5.0.2 on 2025-11-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_classdata_subject_alter_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='unit_name',
            field=models.CharField(choices=[('PLM', "Philosophical Inquiry and Life's Meanings"), ('AEX', 'Aesthetic Exploration'), ('HCO', 'Historical Consciousness'), ('SI1', 'Scientific Inquiry I'), ('SI2', 'Scientific Inquiry II'), ('SO1', 'Social Inquiry I'), ('SO2', 'Social Inquiry II'), ('QR1', 'Quantitative Reasoning I'), ('QR2', 'Quantitative Reasoning II'), ('IIC', 'Individual in the Community'), ('GCI', 'Global Citizenship and Interpersonal Literacy'), ('ETR', 'Ethical Reasoning'), ('FYW', 'First-Year Writing Seminar'), ('WRI', 'Writing, Research, and Inquiry'), ('WIN', 'Writing Intensive Course'), ('OSC', 'Oral and/or Signed Communication'), ('DME', 'Digital/Multimedia Expression'), ('CRT', 'Critical Thinking'), ('RIL', 'Research and Information Literacy'), ('TWC', 'Teamwork/Collaboration'), ('CRI', 'Creativity/Innovation')], max_length=3, unique=True),
        ),
    ]
