# Generated by Django 5.0.2 on 2025-11-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_hub_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_offered', models.CharField(choices=[('spring', 'Spring'), ('fall', 'Fall'), ('summer', 'Summer')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.CharField(blank=True, default='4', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='offered',
            field=models.ManyToManyField(to='Core.offered'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(to='Core.professor'),
        ),
    ]
