# Generated by Django 5.2.8 on 2025-11-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(to='Core.professor'),
        ),
    ]
