# Generated by Django 5.0.2 on 2025-11-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_offered_professor_alter_course_credits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offered',
            options={'verbose_name_plural': 'Semesters Offered'},
        ),
    ]
