# Generated by Django 5.0.2 on 2025-11-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_offered_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offered',
            name='semester_offered',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer', 'Summer')], max_length=10, unique=True),
        ),
    ]
