# Generated by Django 5.0.2 on 2025-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_offered_semester_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offered_next_semester',
            field=models.BooleanField(default=False),
        ),
    ]
