# Generated by Django 5.2.8 on 2025-11-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_course_professor'),
        ('Core', '0015_course_offered_next_semester'),
    ]

    operations = [
    ]
